export enum Room {
  Hall = 'hall',
  BoilerRoom = 'boiler-room',
  LivingRoom = 'living-room',
  DiningRoom = 'dining-room',
  LaundryRoom = 'laundry-room',
  Office = 'office',
  Garage = 'garage',
  Bedroom = 'bedroom',
  ToiletDownstairs = 'toilet-downstairs',
  Stairs = 'stairs',
  Kitchen = 'kitchen',
  Larder = 'larder',
  AboveGarageRoom = 'above-garage-room',
  Gym = 'gym',
  GuestRoom = 'guest-room',
}
