graph TD
    Hue[PhilipsHue] --> |Zigbee| deconz
    XaiomiSensors --> |Zigbee| deconz
    deconz --> |Websocket| Ws2Mqtt
    Ws2Mqtt --> MQTT{MQTT}
    Mqtt2Http --> |HTTP| deconz
    MQTT --> Mqtt2Http
    MQTT --> statsCollector
    statsCollector --> |HTTP|InfluxDB
    InfluxDB --> Grafana
    tuyaPlugs --> |tuyaPlugs/+/status|MQTT
    SmartPlugs --> |tcp/udp|tuyaPlugs
    MQTT --> tuyaPlugs
    openWeather --> |HTTP|api.openweathermap.org
    openWeather --> |forecast/+|MQTT
    pollutionReports --> MQTT
    pollutionReports --> |HTTP|api.airvisual.com
    pollutionReports --> |HTTP|api.waqi.info
    smarterCoffeeMachine --> MQTT
    smarterCoffeeMachine --> |TCP| CoffeeMachine
    LG2MQTT --> MQTT
    LG2MQTT --> |websockets| LGSmartTV
